### ISSUE TITLE
overflow-x apparently is in the wrong element

### ISSUE THREAD

**Issue by dudusotero** [caki0915/gatsby-starter-redux#1]
I was checking your demo out of curiosity and noticed that overflow-x is being applied to the wrong element.

![image](https://user-images.githubusercontent.com/7073199/46186789-c1705100-c2b6-11e8-807f-1b60ce1c124b.png)

I imagine that if you add overflow-x: hidden to the parent, it will fix the scrollbar problem.

😋

**Comment by caki0915** [comment]
Thanks, @dudusotero  good catch!  Should be fixed now :)
